/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devexperts.switchboard.integrations.teamcity.swagger.codegen.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import io.swagger.annotations.ApiModelProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.Objects;

/**
 * AgentPool
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-01T01:12:43.660+03:00")
@XmlRootElement(name = "agentPool")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "agentPool")
@JsonIgnoreProperties(ignoreUnknown = true)
public class AgentPool {
    @JsonProperty("id")
    @JacksonXmlProperty(isAttribute = true, localName = "id")
    @XmlAttribute(name = "id")
    private Integer id = null;

    @JsonProperty("name")
    @JacksonXmlProperty(isAttribute = true, localName = "name")
    @XmlAttribute(name = "name")
    private String name = null;

    @JsonProperty("href")
    @JacksonXmlProperty(isAttribute = true, localName = "href")
    @XmlAttribute(name = "href")
    private String href = null;

    @JsonProperty("maxAgents")
    @JacksonXmlProperty(isAttribute = true, localName = "maxAgents")
    @XmlAttribute(name = "maxAgents")
    private Integer maxAgents = null;

    @JsonProperty("agents")
    @JacksonXmlProperty(localName = "agents")
    @XmlElement(name = "agents")
    private Agents agents = null;

    @JsonProperty("locator")
    @JacksonXmlProperty(isAttribute = true, localName = "locator")
    @XmlAttribute(name = "locator")
    private String locator = null;

    public AgentPool id(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(value = "")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public AgentPool name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public AgentPool href(String href) {
        this.href = href;
        return this;
    }

    /**
     * Get href
     *
     * @return href
     **/
    @ApiModelProperty(value = "")
    public String getHref() {
        return href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public AgentPool maxAgents(Integer maxAgents) {
        this.maxAgents = maxAgents;
        return this;
    }

    /**
     * Get maxAgents
     *
     * @return maxAgents
     **/
    @ApiModelProperty(value = "")
    public Integer getMaxAgents() {
        return maxAgents;
    }

    public void setMaxAgents(Integer maxAgents) {
        this.maxAgents = maxAgents;
    }

    public AgentPool agents(Agents agents) {
        this.agents = agents;
        return this;
    }

    /**
     * Get agents
     *
     * @return agents
     **/
    @ApiModelProperty(value = "")
    public Agents getAgents() {
        return agents;
    }

    public void setAgents(Agents agents) {
        this.agents = agents;
    }

    public AgentPool locator(String locator) {
        this.locator = locator;
        return this;
    }

    /**
     * Get locator
     *
     * @return locator
     **/
    @ApiModelProperty(value = "")
    public String getLocator() {
        return locator;
    }

    public void setLocator(String locator) {
        this.locator = locator;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgentPool agentPool = (AgentPool) o;
        return Objects.equals(this.id, agentPool.id) &&
                Objects.equals(this.name, agentPool.name) &&
                Objects.equals(this.href, agentPool.href) &&
                Objects.equals(this.maxAgents, agentPool.maxAgents) &&
                Objects.equals(this.agents, agentPool.agents) &&
                Objects.equals(this.locator, agentPool.locator);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, href, maxAgents, agents, locator);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AgentPool {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    href: ").append(toIndentedString(href)).append("\n");
        sb.append("    maxAgents: ").append(toIndentedString(maxAgents)).append("\n");
        sb.append("    agents: ").append(toIndentedString(agents)).append("\n");
        sb.append("    locator: ").append(toIndentedString(locator)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

