/*
 * TeamCity REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2018.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.devexperts.switchboard.integrations.teamcity.swagger.codegen.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import io.swagger.annotations.ApiModelProperty;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Properties
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-01T01:12:43.660+03:00")
@XmlRootElement(name = "properties")
@XmlAccessorType(XmlAccessType.FIELD)
@JacksonXmlRootElement(localName = "properties")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Properties {
    @JsonProperty("count")
    @JacksonXmlProperty(isAttribute = true, localName = "count")
    @XmlAttribute(name = "count")
    private Integer count = null;

    @JsonProperty("href")
    @JacksonXmlProperty(isAttribute = true, localName = "href")
    @XmlAttribute(name = "href")
    private String href = null;

    @JsonProperty("property")
    // Is a container wrapped=false
    // items.name=property items.baseName=property items.xmlName= items.xmlNamespace=
    // items.example= items.type=Property
    @XmlElement(name = "property")
    private List<Property> property = null;

    public Properties count(Integer count) {
        this.count = count;
        return this;
    }

    /**
     * Get count
     *
     * @return count
     **/
    @ApiModelProperty(value = "")
    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Properties href(String href) {
        this.href = href;
        return this;
    }

    /**
     * Get href
     *
     * @return href
     **/
    @ApiModelProperty(value = "")
    public String getHref() {
        return href;
    }

    public void setHref(String href) {
        this.href = href;
    }

    public Properties property(List<Property> property) {
        this.property = property;
        return this;
    }

    public Properties addPropertyItem(Property propertyItem) {
        if (this.property == null) {
            this.property = new ArrayList<Property>();
        }
        this.property.add(propertyItem);
        return this;
    }

    /**
     * Get property
     *
     * @return property
     **/
    @ApiModelProperty(value = "")
    public List<Property> getProperty() {
        return property;
    }

    public void setProperty(List<Property> property) {
        this.property = property;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Properties properties = (Properties) o;
        return Objects.equals(this.count, properties.count) &&
                Objects.equals(this.href, properties.href) &&
                Objects.equals(this.property, properties.property);
    }

    @Override
    public int hashCode() {
        return Objects.hash(count, href, property);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Properties {\n");

        sb.append("    count: ").append(toIndentedString(count)).append("\n");
        sb.append("    href: ").append(toIndentedString(href)).append("\n");
        sb.append("    property: ").append(toIndentedString(property)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

